kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nexoedge-k8s-example
nodes:
# the control plane node config
- role: control-plane
  extraPortMappings:
  - containerPort: 30445
    hostPort: 445
## the three workers
#- role: worker
#- role: worker
#- role: worker
