apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexoedge-metastore-pv
  namespace: nexoedge
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/proxy-metastore

