apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexoedge-cifs-meta-pv
  namespace: nexoedge
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data/cifs-meta

